AWSTemplateFormatVersion: "2010-09-09"

# aws cloudformation deploy --template-file samples/test.yml --stack-name test

Resources:
  Test:
    Type: SPRT::CrossStack::Executor
    Properties:
      AccountId: 123456789012
      Region: eu-central-1
      AssumeRoleName: SomeSubPath/SomeCrossAccessRole
      CfnTemplate: ...
      LogLevel: 10
